version: "3.9"

services:
  web:
    container_name: exampleapp
    restart: always
    build: .
    ports:
        - "5000:3000"
    links: 
        - mongodb
    volumes:
        - /app
  mongodb:
    container_name: mymongodatabase
    image: mongo
    ports:
        - "27018:27017"